// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wusainegllejbzyttjrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1c2FpbmVnbGxlamJ6eXR0anJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NTkzMTIsImV4cCI6MjA1NTAzNTMxMn0.-PO5tt1YGq5HwcHVJ9lFTYbFtBpGVKCH1_m43ci3fNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);